Repository sanscript-tech/hacking-tools-scripts, pull requests merged in 2020-10, with the labels that each got.

#34 Added script for hashing files
  Hashing file/app.py
  Hashing file/readme.md
  Hashing file/requirements.txt
Labels: Change requested

#42 Added program to get system information
  system information/app.py
  system information/readme.md
  system information/requirements.txt
Labels: Change requested

#37 Added script for primality test in c++
  primality.txt
  primalitytest.cpp
  primalitytestdocument.txt
Labels: C++, Change requested, readme-missing

#46 Added script for detecting strength of password
  Password_Checker/README.md
  Password_Checker/output_password_checker.png
  Password_Checker/password_checker.py
Labels: Change requested

#62 Port-Scanner-Added
  Port-Scanner/PortScanner.py
  Port-Scanner/README.md
  Port-Scanner/images/portscanner1.png
  Port-Scanner/images/portscanner2.png
  Port-Scanner/requirements.txt
Labels: Change requested

#50 Modular exponentiation with Python
  Modular Exponentiation/REAMDE.md
  Modular Exponentiation/iterative.PNG
  Modular Exponentiation/iterative.py
  Modular Exponentiation/recursive.PNG
  Modular Exponentiation/recursive.py
Labels: Change requested

#86 Links for webpage
  JavaScript/Links-From-Webpage/Readme.md
  JavaScript/Links-From-Webpage/script.js
Labels: Change requested

#84 BMI-Calculator-Added
  Python/BMICalculator/README.md
  Python/BMICalculator/bmi-calculator.py
  Python/BMICalculator/images/bmi-calculator.png
  Python/BMICalculator/requirements.txt
Labels: Change requested

#119 Ticketing model in simpy
  Python/simpy/README.md
  Python/simpy/simpy_1.png
  Python/simpy/ticketing_model.py
Labels: Change requested

#127 Sql to csv
  Python/sql_to_csv_/README.md
  Python/sql_to_csv_/Screenshot.png
  Python/sql_to_csv_/requirements.txt
  Python/sql_to_csv_/sql_to_csv.py
Labels: Change requested

#122 Amazon price tracker #97
  Python/Amazon-Price-Tracker/README.md
  Python/Amazon-Price-Tracker/assets/change.png
  Python/Amazon-Price-Tracker/assets/confirm.png
  Python/Amazon-Price-Tracker/assets/email.png
  Python/Amazon-Price-Tracker/assets/lesssecure.png
  Python/Amazon-Price-Tracker/assets/mail.png
  Python/Amazon-Price-Tracker/assets/myagent.png
  Python/Amazon-Price-Tracker/assets/range.png
  Python/Amazon-Price-Tracker/assets/single.png
  Python/Amazon-Price-Tracker/mail_in_python.py
  Python/Amazon-Price-Tracker/price_logger.txt
  Python/Amazon-Price-Tracker/price_tracker.py
Labels: Change requested

#136 Return Geolocation of IP addresses in a CSV file.
  Python/CSV-IP-geolocation/IP_data.csv
  Python/CSV-IP-geolocation/README.md
  Python/CSV-IP-geolocation/app.py
  Python/CSV-IP-geolocation/csv-ip-op.png
Labels: Change requested

#135 Instagram bot that list all accounts that you follow, which don't follow back
  Python/Instagram_Bot/README.md
  Python/Instagram_Bot/instagram_bot.py
Labels: Change requested

#141 Human detection
  Python/human-detection/README.md
  Python/human-detection/human-detection.py
  Python/human-detection/images/result.png
  Python/human-detection/images/sample.jpg
  Python/human-detection/requirements.txt
Labels: Change requested

#120 Python script to shut down your System
  Python/Shut_down_your_system/README.md
  Python/Shut_down_your_system/images/ss1.jpg
  Python/Shut_down_your_system/images/ss2.jpg
  Python/Shut_down_your_system/images/ss3.jpg
  Python/Shut_down_your_system/images/ss4.jpg
  Python/Shut_down_your_system/images/ss5.jpeg
  Python/Shut_down_your_system/images/ss6.jpeg
  Python/Shut_down_your_system/shutdown.py
Labels: Change requested

#140 Network Usage Notifier
  Python/Network-Usage-Notifier/README.md
  Python/Network-Usage-Notifier/app.py
  Python/Network-Usage-Notifier/images/icon.png
  Python/Network-Usage-Notifier/images/op_init.png
  Python/Network-Usage-Notifier/images/op_notif.png
  Python/Network-Usage-Notifier/install.py
  Python/Network-Usage-Notifier/requirements.txt
Labels: Change requested

#156 Windows Reverse Shell
  Python/Windows-Reverse-Shell/README.md
  Python/Windows-Reverse-Shell/attacker.py
  Python/Windows-Reverse-Shell/images/attacker.png
  Python/Windows-Reverse-Shell/images/victim.png
  Python/Windows-Reverse-Shell/victim.py
Labels: Change requested

#148 Geo-location from IP address
  Python/Location-based-on-IP/README.md
  Python/Location-based-on-IP/assets/error.PNG
  Python/Location-based-on-IP/assets/ip.PNG
  Python/Location-based-on-IP/assets/location.PNG
  Python/Location-based-on-IP/get_coordinates.py
Labels: Change requested

#151 added emails extractor
  Python/Emails_extractor_from_web_pages/README.md
  Python/Emails_extractor_from_web_pages/emails_extractor.py
  Python/Emails_extractor_from_web_pages/requirements.txt
Labels: Change requested

#51 Implementation of Keylogger.
  Keylogger/.gitignore
  Keylogger/README.md
  Keylogger/img01.jpg
  Keylogger/img02.jpg
  Keylogger/img03.jpg
  Keylogger/img04.png
  Keylogger/img05.png
  Keylogger/img06.png
  Keylogger/requirements.txt
  Keylogger/script.py
Labels: Change requested

#162 Sejalshri crt
  C/chinese_remainder_theorem/CRT README.md
  C/chinese_remainder_theorem/CRT.c
Labels: C++, Change requested

#163 Whatsapp automation to send bulk messages
  Python/whatsapp-automation/README.md
  Python/whatsapp-automation/ezgif.gif
  Python/whatsapp-automation/message-automation.py
  Python/whatsapp-automation/requirements.txt
Labels: Change requested

#154 Chinese Remainder Theorem added
  Java/ChineseRemainderTheorem/CRT.java
  Java/ChineseRemainderTheorem/README.md
  Java/ChineseRemainderTheorem/RelevanceInCryptography.txt
Labels: Change requested

#176 Twitter automation
  Python/twitter-automation/README.md
  Python/twitter-automation/images/Screenshot (476)_LI.jpg
  Python/twitter-automation/images/apply_to_make_a_bot.png
  Python/twitter-automation/images/confirm_email.png
  Python/twitter-automation/images/edit_app_permissions.png
  Python/twitter-automation/images/enter_app_name.png
  Python/twitter-automation/images/enter_info.png
  Python/twitter-automation/images/keys.png
  Python/twitter-automation/images/open_dev_link.png
  Python/twitter-automation/images/skip to dashboard.jpg
  Python/twitter-automation/requirements.txt
  Python/twitter-automation/tweet.py
Labels: Change requested

#191 Counting days
  JavaScript/Counting_Days/Readme.md
  JavaScript/Counting_Days/script.js
Labels: Change requested

#197 Program timing
  C++/program-timing/README.md
  C++/program-timing/Screenshot.png
  C++/program-timing/time_script.cpp
  Python/whatsapp-automation/debug.log
Labels: Change requested

#172 Scrap top 250 movies from IMDB and generate a CSV file for it.
  Python/Scrap_Top_250_Movies/README.md
  Python/Scrap_Top_250_Movies/Scrap_movies_from_imdb.ipynb
  Python/Scrap_Top_250_Movies/output.jpg
Labels: Change requested

#208 Automate Telegram #160
  Python/Automate-Telegram/README.md
  Python/Automate-Telegram/assets/code.png
  Python/Automate-Telegram/assets/login.png
  Python/Automate-Telegram/assets/send.png
  Python/Automate-Telegram/automate_telegram.py
Labels: Change requested

#199 Xss scanner ninjavin
  Python/XSS-Check/README.md
  Python/XSS-Check/XSS-Check.py
  Python/XSS-Check/images/xss-check.png
  Python/XSS-Check/payloads.txt
  Python/XSS-Check/requirements.txt
Labels: Change requested

#212 Image Steganography along with Encryption
  Python/Image-Steganography/README.md
  Python/Image-Steganography/hide.py
  Python/Image-Steganography/images/hiding.png
  Python/Image-Steganography/images/retrieving.png
  Python/Image-Steganography/images/sample.png
  Python/Image-Steganography/images/sample_secret.png
  Python/Image-Steganography/info.txt
  Python/Image-Steganography/key
  Python/Image-Steganography/requirements.txt
  Python/Image-Steganography/retrieve.py
Labels: Change requested
