Repository sanscript-tech/hacking-tools-scripts, pull requests merged in 2020-11, with the labels that each got.

#171 Added automating script for Zoom
  Python/zoom_automation/README.md
  Python/zoom_automation/join_btn.png
  Python/zoom_automation/join_button_img.png
  Python/zoom_automation/main.py
  Python/zoom_automation/media_btn.png
  Python/zoom_automation/meeting_id_btn.png
  Python/zoom_automation/meeting_pswd.png
  Python/zoom_automation/schedule.csv
Labels: Change requested

#168 Launching Other Programs from Python
  Launching other Programs/README.md
  Launching other Programs/main.py
Labels: Change requested

#230 News assistant
  Python/news-assistant/README.md
  Python/news-assistant/news.py
Labels: Change requested

#224 Script to automate code submission on codechef
  Python/CodeChef_Selenium/README.md
  Python/CodeChef_Selenium/codechef_selenium_script.py
Labels: Change requested

#229 Checking Timing of a Program in C
  .gitignore
  C/Program-Timer/README.md
  C/Program-Timer/output.png
  C/Program-Timer/timer.c
Labels: Change requested

#223 Added Sympy
  Python/Sympy/.ipynb_checkpoints/Sympy-checkpoint.ipynb
  Python/Sympy/README.md
  Python/Sympy/Sympy.ipynb
Labels: Change requested

#242 News assistant in node
  JavaScript/news-assistant/.gitignore
  JavaScript/news-assistant/README.md
  JavaScript/news-assistant/index.js
  JavaScript/news-assistant/news-assistant/index.js
  JavaScript/news-assistant/package.json
Labels: Change requested

#246 Multithreaded Port Scanner
  Python/Multithreaded-Port-Scanner/README.md
  Python/Multithreaded-Port-Scanner/images/output1.png
  Python/Multithreaded-Port-Scanner/images/output2.png
  Python/Multithreaded-Port-Scanner/scan-ports.py
Labels: Change requested

#266 Amazon top 5 products listing using selenium in java
  Java/AmazonProductList/AmazonProductListing/.gitignore
  Java/AmazonProductList/AmazonProductListing/.idea/.gitignore
  Java/AmazonProductList/AmazonProductListing/.idea/compiler.xml
  Java/AmazonProductList/AmazonProductListing/.idea/gradle.xml
  Java/AmazonProductList/AmazonProductListing/.idea/jarRepositories.xml
  Java/AmazonProductList/AmazonProductListing/.idea/misc.xml
  Java/AmazonProductList/AmazonProductListing/.idea/vcs.xml
  Java/AmazonProductList/AmazonProductListing/README.md
  Java/AmazonProductList/AmazonProductListing/build.gradle
  Java/AmazonProductList/AmazonProductListing/gradlew
  Java/AmazonProductList/AmazonProductListing/gradlew.bat
  Java/AmazonProductList/AmazonProductListing/settings.gradle
  Java/AmazonProductList/AmazonProductListing/src/main/java/AmazonProductListClass.java
Labels: Change requested, Hard

#289 Changes done (size of folder)
  C/sizeofdirectory/README.md
  C/sizeofdirectory/sizeoffolder.c
Labels: Change requested

#320 Webpage to pdf
  Python/webpage-to-pdf/README.md
  Python/webpage-to-pdf/convert.py
Labels: Easy

#324 toonify any image using open cv
  Python/ToonifyImage/Readme.MD
  Python/ToonifyImage/images/output.jpg
  Python/ToonifyImage/images/rohit.png
  Python/ToonifyImage/output.jpg
  Python/ToonifyImage/toonify.py
Labels: Change requested

#327 A sudoku Solver
  Python/SudokuSolver/Readme.MD
  Python/SudokuSolver/images/image1.png
  Python/SudokuSolver/images/image2.png
  Python/SudokuSolver/sudoku.py
Labels: Change requested

#285 python script for shapes
  Python/shape-detection/README.md
  Python/shape-detection/Shape_Detection.py
  Python/shape-detection/images/Test1.png
  Python/shape-detection/images/Test2.png
  Python/shape-detection/images/Test3.png
Labels: Change requested

#292 Added image to sketch
  Python/Image_Sketch/README.md
  Python/Image_Sketch/Sketch.py
  Python/Image_Sketch/obama.jpg
  Python/Image_Sketch/sketch.jpg
Labels: Change requested

#328 Number of contributors and size of a Github repository
  Python/Github-repo-and-contributors/README.md
  Python/Github-repo-and-contributors/get_info.py
  Python/Github-repo-and-contributors/github.PNG
  Python/Repo-size-and-contributors/get-info.py
Labels: Change requested

#333 Spotify Downloader
  Python/Spotify-Downloader/README.md
  Python/Spotify-Downloader/app.py
  Python/Spotify-Downloader/output.png
  Python/Spotify-Downloader/requirements.txt
Labels: Change requested

#339 Get Weather details in C
  C/Weather-Details/.gitignore
  C/Weather-Details/Makefile
  C/Weather-Details/README.md
  C/Weather-Details/output.png
  C/Weather-Details/weather
  C/Weather-Details/weather.c
Labels: C language, Change requested, documentation

#354 Web Technology Detector Added in NodeJS
  JavaScript/Web-Technologies-Detector/.gitignore
  JavaScript/Web-Technologies-Detector/README.md
  JavaScript/Web-Technologies-Detector/images/web-tech.png
  JavaScript/Web-Technologies-Detector/index.js
Labels: Medium Level

#360 Script to check if file exists python
  Python/check-file-exists/README.md
  Python/check-file-exists/Screenshot (587).png
  Python/check-file-exists/check.py
Labels: Change requested

#363 extract files from zip in python
  Python/Extract_Contents_of_Zip/Readme.md
  Python/Extract_Contents_of_Zip/script.py
Labels: Change requested

#381 text to speech
  JavaScript/Text_to_Speech_CLI/Readme.md
  JavaScript/Text_to_Speech_CLI/requirements
  JavaScript/Text_to_Speech_CLI/script.js
Labels: Change requested

#391 Currency Converted CLI Python Added
  Python/Currency-Converter/README.md
  Python/Currency-Converter/converter.py
  Python/Currency-Converter/images/currency.png
Labels: Change requested

#394 PDF watermark added
  Python/PDFWatermark/README.md
  Python/PDFWatermark/pdf.jpeg
  Python/PDFWatermark/pdf.py
Labels: Change requested
